apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q6uu1glli-java-quarkus
  janus-idp.io/tekton: q6uu1glli-java-quarkus
  backstage.io/kubernetes-id: q6uu1glli-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: q6uu1glli-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
